spring.profiles.active: development
spring:
  mvc:
    favicon:
      enabled: true
  jmx:
    default-domain: local.branon.com
    enabled: true
  http:
    multipart:
      enabled: true
      location: d:\
      max-file-size: 100Mb
      max-request-size: 100Mb

---

spring:
  profiles: development
  http:
      encoding:
        enabled: true
        force: true
        charset: UTF-8
  messages:
    encoding: UTF-8
    cache-seconds: 3600
    fallback-to-system-locale: true
  session:
    store-type: hash_map
  resources:
    chain:
      enabled: true
      cache: true
      strategy:
        content:
          enabled: true
        fixed:
          enabled: true
  jpa:
    show-sql: true
logging:
  level:
    org.thymeleaf: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.h2.server.web: INFO
    com.brandon: debug
    org.apache.coyote: off
---

spring:
  profiles: production
  http:
      encoding:
        enabled: true
        force: true
        charset: UTF-8
  messages:
    encoding: UTF-8
    cache-seconds: -1
    fallback-to-system-locale: true
  session:
    store-type: hash_map
  resources:
    chain:
      enabled: true
      cache: true
      strategy:
        content:
          enabled: true
        fixed:
          enabled: true
    cache-period: 31556926
  jpa:
    show-sql: false
logging:
  config: classpath:logs/logback-spring.xml

---